server:
  port: 8081
spring:
  application:
    name:rest-with-spring-boot-and-java-wanderlei
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest-with_spring__and-java-wanderlei?useTimezone=true&serverTimezone=UTC
    username: wjb
    password: Nazlob4991@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
    br.com.wanderlei: INFO